// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FootballCards.Data;

#nullable disable

namespace FootballCards.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418213219_UpdateCardDataAndSeed")]
    partial class UpdateCardDataAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballCards.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIcon")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OvrRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardImage = "/cards/France/zidaneCard.png",
                            Country = "France",
                            IsIcon = true,
                            Name = "Zinedine Zidane",
                            OvrRating = 94
                        },
                        new
                        {
                            Id = 2,
                            CardImage = "/cards/France/thierryCard.png",
                            Country = "France",
                            IsIcon = true,
                            Name = "Therry Henry",
                            OvrRating = 92
                        },
                        new
                        {
                            Id = 3,
                            CardImage = "/cards/France/mbappeCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Kylian Mbappe",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 4,
                            CardImage = "/cards/France/dembeleCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Ousmane Dembele",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 5,
                            CardImage = "/cards/France/maignanCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Mike Maignan",
                            OvrRating = 87
                        },
                        new
                        {
                            Id = 6,
                            CardImage = "/cards/France/oliseCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Michael Olise",
                            OvrRating = 86
                        },
                        new
                        {
                            Id = 7,
                            CardImage = "/cards/France/benzemaCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Karem Benzema",
                            OvrRating = 85
                        },
                        new
                        {
                            Id = 8,
                            CardImage = "/cards/France/cherkiCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Rayan Cherki",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 9,
                            CardImage = "/cards/France/giroudCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Olivier Giroud",
                            OvrRating = 79
                        },
                        new
                        {
                            Id = 10,
                            CardImage = "/cards/France/zoumaCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Kurt Zouma",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 29,
                            CardImage = "/cards/Brazil/peleCard.png",
                            Country = "Brazil",
                            IsIcon = true,
                            Name = "Pelé",
                            OvrRating = 95
                        },
                        new
                        {
                            Id = 30,
                            CardImage = "/cards/Brazil/ronaldonazarioCard.png",
                            Country = "Brazil",
                            IsIcon = true,
                            Name = "Ronaldo",
                            OvrRating = 93
                        },
                        new
                        {
                            Id = 27,
                            CardImage = "/cards/Brazil/ronaldinhoCard.png",
                            Country = "Brazil",
                            IsIcon = true,
                            Name = "Ronaldinho",
                            OvrRating = 92
                        },
                        new
                        {
                            Id = 20,
                            CardImage = "/cards/Brazil/vinijrCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Vinicius Jr",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 24,
                            CardImage = "/cards/Brazil/alissonCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Alisson",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 21,
                            CardImage = "/cards/Brazil/neymarCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Neymar Jr",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 33,
                            CardImage = "/cards/Brazil/taliscaCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Talisca",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 26,
                            CardImage = "/cards/Brazil/casemiroCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Casemiro",
                            OvrRating = 80
                        },
                        new
                        {
                            Id = 32,
                            CardImage = "/cards/Brazil/danteCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Dante",
                            OvrRating = 78
                        },
                        new
                        {
                            Id = 31,
                            CardImage = "/cards/Brazil/endrickCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Endrick",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 11,
                            CardImage = "/cards/Argentina/messiCard.png",
                            Country = "Argentina",
                            IsIcon = false,
                            Name = "Lionel Messi",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 12,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = false,
                            Name = "Cristiano Ronaldo",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 13,
                            CardImage = "tbd",
                            Country = "Belgium",
                            IsIcon = false,
                            Name = "Kevin De Bruyne",
                            OvrRating = 92
                        },
                        new
                        {
                            Id = 14,
                            CardImage = "tbd",
                            Country = "Norway",
                            IsIcon = false,
                            Name = "Erling Haaland",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 15,
                            CardImage = "tbd",
                            Country = "Egypt",
                            IsIcon = false,
                            Name = "Mohamed Salah",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 16,
                            CardImage = "tbd",
                            Country = "Netherlands",
                            IsIcon = false,
                            Name = "Virgil van Dijk",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 17,
                            CardImage = "tbd",
                            Country = "Belgium",
                            IsIcon = false,
                            Name = "Thibaut Courtois",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 18,
                            CardImage = "tbd",
                            Country = "Poland",
                            IsIcon = false,
                            Name = "Robert Lewandowski",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 19,
                            CardImage = "tbd",
                            Country = "Croatia",
                            IsIcon = false,
                            Name = "Luka Modric",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 22,
                            CardImage = "tbd",
                            Country = "South Korea",
                            IsIcon = false,
                            Name = "Heung Min Son",
                            OvrRating = 88
                        },
                        new
                        {
                            Id = 23,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Harry Kane",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 25,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = false,
                            Name = "Joshua Kimmich",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 28,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = false,
                            Name = "Ruben Dias",
                            OvrRating = 88
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
