// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FootballCards.Data;

#nullable disable

namespace FootballCards.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409160532_SimplifyCardModel")]
    partial class SimplifyCardModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballCards.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OvrRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardImage = "/cards/messi.png",
                            Name = "Lionel Messi",
                            OvrRating = 94
                        },
                        new
                        {
                            Id = 2,
                            CardImage = "tbd",
                            Name = "Cristiano Ronaldo",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 3,
                            CardImage = "/cards/mbappeCard.png",
                            Name = "Kylian Mbappe",
                            OvrRating = 93
                        },
                        new
                        {
                            Id = 4,
                            CardImage = "tbd",
                            Name = "Kevin De Bruyne",
                            OvrRating = 92
                        },
                        new
                        {
                            Id = 5,
                            CardImage = "tbd",
                            Name = "Erling Haaland",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 6,
                            CardImage = "tbd",
                            Name = "Mohamed Salah",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 7,
                            CardImage = "tbd",
                            Name = "Virgil van Dijk",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 8,
                            CardImage = "tbd",
                            Name = "Thibaut Courtois",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 9,
                            CardImage = "tbd",
                            Name = "Robert Lewandowski",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 10,
                            CardImage = "tbd",
                            Name = "Karem Benzema",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 11,
                            CardImage = "tbd",
                            Name = "Luka Modric",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 12,
                            CardImage = "tbd",
                            Name = "Vinicius Jr",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 13,
                            CardImage = "tbd",
                            Name = "Neymar Jr",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 14,
                            CardImage = "tbd",
                            Name = "Heung Min Son",
                            OvrRating = 88
                        },
                        new
                        {
                            Id = 15,
                            CardImage = "tbd",
                            Name = "Harry Kane",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 16,
                            CardImage = "tbd",
                            Name = "Alisson",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 17,
                            CardImage = "tbd",
                            Name = "Joshua Kimmich",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 18,
                            CardImage = "tbd",
                            Name = "Casemiro",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 19,
                            CardImage = "tbd",
                            Name = "Ederson",
                            OvrRating = 88
                        },
                        new
                        {
                            Id = 20,
                            CardImage = "tbd",
                            Name = "Ruben Dias",
                            OvrRating = 88
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
