// <auto-generated />
using FootballCards.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballCards.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballCards.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIcon")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OvrRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardImage = "/cards/France/zidaneCard.png",
                            Country = "France",
                            IsIcon = true,
                            Name = "Zinedine Zidane",
                            OvrRating = 94
                        },
                        new
                        {
                            Id = 2,
                            CardImage = "/cards/France/thierryCard.png",
                            Country = "France",
                            IsIcon = true,
                            Name = "Therry Henry",
                            OvrRating = 92
                        },
                        new
                        {
                            Id = 3,
                            CardImage = "/cards/France/mbappeCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Kylian Mbappe",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 4,
                            CardImage = "/cards/France/dembeleCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Ousmane Dembele",
                            OvrRating = 88
                        },
                        new
                        {
                            Id = 5,
                            CardImage = "/cards/France/maignanCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Mike Maignan",
                            OvrRating = 86
                        },
                        new
                        {
                            Id = 6,
                            CardImage = "/cards/France/oliseCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Michael Olise",
                            OvrRating = 85
                        },
                        new
                        {
                            Id = 7,
                            CardImage = "/cards/France/benzemaCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Karem Benzema",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 8,
                            CardImage = "/cards/France/cherkiCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Rayan Cherki",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 9,
                            CardImage = "/cards/France/giroudCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Olivier Giroud",
                            OvrRating = 79
                        },
                        new
                        {
                            Id = 10,
                            CardImage = "/cards/France/zoumaCard.png",
                            Country = "France",
                            IsIcon = false,
                            Name = "Kurt Zouma",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 11,
                            CardImage = "/cards/Brazil/peleCard.png",
                            Country = "Brazil",
                            IsIcon = true,
                            Name = "Pelé",
                            OvrRating = 96
                        },
                        new
                        {
                            Id = 12,
                            CardImage = "/cards/Brazil/ronaldonazarioCard.png",
                            Country = "Brazil",
                            IsIcon = true,
                            Name = "Ronaldo",
                            OvrRating = 93
                        },
                        new
                        {
                            Id = 13,
                            CardImage = "/cards/Brazil/ronaldinhoCard.png",
                            Country = "Brazil",
                            IsIcon = true,
                            Name = "Ronaldinho",
                            OvrRating = 92
                        },
                        new
                        {
                            Id = 14,
                            CardImage = "/cards/Brazil/vinijrCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Vinicius Jr",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 15,
                            CardImage = "/cards/Brazil/alissonCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Alisson",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 16,
                            CardImage = "/cards/Brazil/neymarCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Neymar Jr",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 17,
                            CardImage = "/cards/Brazil/taliscaCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Talisca",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 18,
                            CardImage = "/cards/Brazil/casemiroCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Casemiro",
                            OvrRating = 80
                        },
                        new
                        {
                            Id = 19,
                            CardImage = "/cards/Brazil/danteCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Dante",
                            OvrRating = 78
                        },
                        new
                        {
                            Id = 20,
                            CardImage = "/cards/Brazil/endrickCard.png",
                            Country = "Brazil",
                            IsIcon = false,
                            Name = "Endrick",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 21,
                            CardImage = "/cards/Argentina/maradonaCard.png",
                            Country = "Argentina",
                            IsIcon = true,
                            Name = "Maradona",
                            OvrRating = 95
                        },
                        new
                        {
                            Id = 22,
                            CardImage = "/cards/Argentina/lautaroCard.png",
                            Country = "Argentina",
                            IsIcon = false,
                            Name = "Lautaro Martinez",
                            OvrRating = 87
                        },
                        new
                        {
                            Id = 23,
                            CardImage = "/cards/Argentina/dybalaCard.png",
                            Country = "Argentina",
                            IsIcon = false,
                            Name = "Paulo Dybala",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 24,
                            CardImage = "/cards/Argentina/messiCard.png",
                            Country = "Argentina",
                            IsIcon = false,
                            Name = "Lionel Messi",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 25,
                            CardImage = "/cards/Argentina/icardiCard.png",
                            Country = "Argentina",
                            IsIcon = false,
                            Name = "Mauro Icardi",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 26,
                            CardImage = "/cards/Argentina/garnachoCard.png",
                            Country = "Argentina",
                            IsIcon = false,
                            Name = "Garnacho",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 27,
                            CardImage = "/cards/Argentina/banegaCard.png",
                            Country = "Argentina",
                            IsIcon = false,
                            Name = "Banega",
                            OvrRating = 73
                        },
                        new
                        {
                            Id = 28,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = true,
                            Name = "Eusébio",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 29,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = false,
                            Name = "Vitihna",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 30,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = false,
                            Name = "Ruben Dias",
                            OvrRating = 85
                        },
                        new
                        {
                            Id = 31,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = false,
                            Name = "Cristiano Ronaldo",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 32,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = false,
                            Name = "Renato Sanches",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 33,
                            CardImage = "tbd",
                            Country = "Portugal",
                            IsIcon = false,
                            Name = "Ricardo Pereira",
                            OvrRating = 73
                        },
                        new
                        {
                            Id = 34,
                            CardImage = "tbd",
                            Country = "Belgium",
                            IsIcon = false,
                            Name = "Thibaut Courtois",
                            OvrRating = 86
                        },
                        new
                        {
                            Id = 35,
                            CardImage = "tbd",
                            Country = "Belgium",
                            IsIcon = false,
                            Name = "Kevin De Bruyne",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 36,
                            CardImage = "tbd",
                            Country = "Belgium",
                            IsIcon = false,
                            Name = "Axel Witsel",
                            OvrRating = 74
                        },
                        new
                        {
                            Id = 37,
                            CardImage = "tbd",
                            Country = "Canada",
                            IsIcon = false,
                            Name = "Alphonso Davies",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 38,
                            CardImage = "tbd",
                            Country = "Netherlands",
                            IsIcon = true,
                            Name = "Cruyff",
                            OvrRating = 94
                        },
                        new
                        {
                            Id = 39,
                            CardImage = "tbd",
                            Country = "Netherlands",
                            IsIcon = false,
                            Name = "Virgil van Dijk",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 40,
                            CardImage = "tbd",
                            Country = "Netherlands",
                            IsIcon = false,
                            Name = "Cody Gakpo",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 41,
                            CardImage = "tbd",
                            Country = "Netherlands",
                            IsIcon = false,
                            Name = "Noa Lang",
                            OvrRating = 80
                        },
                        new
                        {
                            Id = 42,
                            CardImage = "tbd",
                            Country = "Netherlands",
                            IsIcon = false,
                            Name = "Georginio Wijnaldum",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 44,
                            CardImage = "tbd",
                            Country = "Mexico",
                            IsIcon = false,
                            Name = "Ochoa",
                            OvrRating = 72
                        },
                        new
                        {
                            Id = 45,
                            CardImage = "tbd",
                            Country = "Mexico",
                            IsIcon = false,
                            Name = "Santiago Giménez",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 46,
                            CardImage = "tbd",
                            Country = "USA",
                            IsIcon = false,
                            Name = "Christian Pulisic",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 47,
                            CardImage = "tbd",
                            Country = "USA",
                            IsIcon = false,
                            Name = "Yunus Musah",
                            OvrRating = 72
                        },
                        new
                        {
                            Id = 48,
                            CardImage = "tbd",
                            Country = "Australia",
                            IsIcon = false,
                            Name = "Mathew Ryan",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 49,
                            CardImage = "tbd",
                            Country = "Iraq",
                            IsIcon = false,
                            Name = "Ali Adnan",
                            OvrRating = 72
                        },
                        new
                        {
                            Id = 50,
                            CardImage = "tbd",
                            Country = "Iran",
                            IsIcon = false,
                            Name = "Mehdi Taremi",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 51,
                            CardImage = "tbd",
                            Country = "Japan",
                            IsIcon = false,
                            Name = "Kaoru Mitoma",
                            OvrRating = 82
                        },
                        new
                        {
                            Id = 52,
                            CardImage = "tbd",
                            Country = "Jordan",
                            IsIcon = false,
                            Name = "Musa Al Tamari",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 53,
                            CardImage = "tbd",
                            Country = "South Korea",
                            IsIcon = false,
                            Name = "Heung Min Son",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 54,
                            CardImage = "tbd",
                            Country = "South Korea",
                            IsIcon = false,
                            Name = "Min Jae Kim",
                            OvrRating = 82
                        },
                        new
                        {
                            Id = 55,
                            CardImage = "tbd",
                            Country = "Saudi Arabia",
                            IsIcon = false,
                            Name = "Salem Al Dawsari",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 56,
                            CardImage = "tbd",
                            Country = "Qatar",
                            IsIcon = false,
                            Name = "Akram Afif",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 57,
                            CardImage = "tbd",
                            Country = "Uzbekistan",
                            IsIcon = false,
                            Name = "Abdukodir Khusanov",
                            OvrRating = 78
                        },
                        new
                        {
                            Id = 58,
                            CardImage = "tbd",
                            Country = "Algeria",
                            IsIcon = false,
                            Name = "Riyad Mahrez",
                            OvrRating = 82
                        },
                        new
                        {
                            Id = 59,
                            CardImage = "tbd",
                            Country = "Algeria",
                            IsIcon = false,
                            Name = "Bentaleb",
                            OvrRating = 76
                        },
                        new
                        {
                            Id = 60,
                            CardImage = "tbd",
                            Country = "Capo Verde",
                            IsIcon = false,
                            Name = "Cabo Verde",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 61,
                            CardImage = "tbd",
                            Country = "Congo DR",
                            IsIcon = false,
                            Name = "Yoane Wissa",
                            OvrRating = 82
                        },
                        new
                        {
                            Id = 62,
                            CardImage = "tbd",
                            Country = "Côte d'Ivoire",
                            IsIcon = true,
                            Name = "Drogba",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 63,
                            CardImage = "tbd",
                            Country = "Côte d'Ivoire",
                            IsIcon = false,
                            Name = "Evan Ndicka",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 64,
                            CardImage = "tbd",
                            Country = "Egypt",
                            IsIcon = false,
                            Name = "Mohamed Salah",
                            OvrRating = 88
                        },
                        new
                        {
                            Id = 65,
                            CardImage = "tbd",
                            Country = "Ghana",
                            IsIcon = false,
                            Name = "Iñaki Williams",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 66,
                            CardImage = "tbd",
                            Country = "Morocco",
                            IsIcon = false,
                            Name = "Achraf Hakimi",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 67,
                            CardImage = "tbd",
                            Country = "Morocco",
                            IsIcon = false,
                            Name = "Brahim Díaz",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 68,
                            CardImage = "tbd",
                            Country = "Senegal",
                            IsIcon = false,
                            Name = "Sadio Mané",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 69,
                            CardImage = "tbd",
                            Country = "South Africa",
                            IsIcon = false,
                            Name = "Siyabonga Ngezana",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 70,
                            CardImage = "tbd",
                            Country = "Tunisia",
                            IsIcon = false,
                            Name = "Ellyes Skhiri",
                            OvrRating = 80
                        },
                        new
                        {
                            Id = 71,
                            CardImage = "tbd",
                            Country = "Curaçao",
                            IsIcon = false,
                            Name = "Riechedly Bazoer",
                            OvrRating = 74
                        },
                        new
                        {
                            Id = 72,
                            CardImage = "tbd",
                            Country = "Haiti",
                            IsIcon = false,
                            Name = "Bellegarde",
                            OvrRating = 76
                        },
                        new
                        {
                            Id = 73,
                            CardImage = "tbd",
                            Country = "Panama",
                            IsIcon = false,
                            Name = "Amir Murillo",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 74,
                            CardImage = "tbd",
                            Country = "Columbia",
                            IsIcon = false,
                            Name = "Luis Díaz",
                            OvrRating = 85
                        },
                        new
                        {
                            Id = 75,
                            CardImage = "tbd",
                            Country = "Ecuador",
                            IsIcon = false,
                            Name = "Moisés Caicedo",
                            OvrRating = 86
                        },
                        new
                        {
                            Id = 76,
                            CardImage = "tbd",
                            Country = "Ecuador",
                            IsIcon = false,
                            Name = "Willian Pacho",
                            OvrRating = 85
                        },
                        new
                        {
                            Id = 77,
                            CardImage = "tbd",
                            Country = "Paraguay",
                            IsIcon = false,
                            Name = "Gamarra",
                            OvrRating = 79
                        },
                        new
                        {
                            Id = 78,
                            CardImage = "tbd",
                            Country = "Uruguay",
                            IsIcon = false,
                            Name = "Federico Valverde",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 79,
                            CardImage = "tbd",
                            Country = "Uruguay",
                            IsIcon = false,
                            Name = "Ronald Araujo",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 80,
                            CardImage = "tbd",
                            Country = "Uruguay",
                            IsIcon = false,
                            Name = "Edinson Cavani",
                            OvrRating = 76
                        },
                        new
                        {
                            Id = 81,
                            CardImage = "tbd",
                            Country = "New Zealand",
                            IsIcon = false,
                            Name = "Chris Wood",
                            OvrRating = 82
                        },
                        new
                        {
                            Id = 82,
                            CardImage = "tbd",
                            Country = "Austria",
                            IsIcon = false,
                            Name = "Konrad Laimer",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 83,
                            CardImage = "tbd",
                            Country = "Bosnia and Herzegovina",
                            IsIcon = false,
                            Name = "Edin Džeko",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 84,
                            CardImage = "tbd",
                            Country = "Croatia",
                            IsIcon = false,
                            Name = "Gvardiol",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 85,
                            CardImage = "tbd",
                            Country = "Croatia",
                            IsIcon = false,
                            Name = "Luka Modric",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 86,
                            CardImage = "tbd",
                            Country = "Czech Republic",
                            IsIcon = false,
                            Name = "Patrik Schick",
                            OvrRating = 86
                        },
                        new
                        {
                            Id = 87,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = true,
                            Name = "Rooney",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 88,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Harry Kane",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 89,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Jude Bellingham",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 90,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Bukayo Saka",
                            OvrRating = 87
                        },
                        new
                        {
                            Id = 91,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Phil Foden",
                            OvrRating = 84
                        },
                        new
                        {
                            Id = 92,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Marcus Rashford",
                            OvrRating = 80
                        },
                        new
                        {
                            Id = 93,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Harry Maguire",
                            OvrRating = 80
                        },
                        new
                        {
                            Id = 94,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Raheem Sterling",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 95,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Jamie Vardy",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 96,
                            CardImage = "tbd",
                            Country = "England",
                            IsIcon = false,
                            Name = "Jesse Lingard",
                            OvrRating = 73
                        },
                        new
                        {
                            Id = 97,
                            CardImage = "tbd",
                            Country = "Sweden",
                            IsIcon = true,
                            Name = "Ibrahimovic",
                            OvrRating = 91
                        },
                        new
                        {
                            Id = 98,
                            CardImage = "tbd",
                            Country = "Sweden",
                            IsIcon = false,
                            Name = "Alexander Isak",
                            OvrRating = 87
                        },
                        new
                        {
                            Id = 99,
                            CardImage = "tbd",
                            Country = "Switzerland",
                            IsIcon = false,
                            Name = "Yann Sommer",
                            OvrRating = 86
                        },
                        new
                        {
                            Id = 100,
                            CardImage = "tbd",
                            Country = "Scotland",
                            IsIcon = false,
                            Name = "Scott McTominay",
                            OvrRating = 85
                        },
                        new
                        {
                            Id = 101,
                            CardImage = "tbd",
                            Country = "Norway",
                            IsIcon = false,
                            Name = "Erling Haaland",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 102,
                            CardImage = "tbd",
                            Country = "Turkey",
                            IsIcon = false,
                            Name = "Hakan Çalhanoğlu",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 103,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = true,
                            Name = "Franz Beckenbauer",
                            OvrRating = 93
                        },
                        new
                        {
                            Id = 104,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = false,
                            Name = "Joshua Kimmich",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 105,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = false,
                            Name = "Musiala",
                            OvrRating = 87
                        },
                        new
                        {
                            Id = 106,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = false,
                            Name = "Manuel Neuer",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 107,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = false,
                            Name = "Gündoğan",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 108,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = false,
                            Name = "Timo Werner",
                            OvrRating = 75
                        },
                        new
                        {
                            Id = 109,
                            CardImage = "tbd",
                            Country = "Germany",
                            IsIcon = false,
                            Name = "Bisseck",
                            OvrRating = 73
                        },
                        new
                        {
                            Id = 110,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = true,
                            Name = "Iniesta",
                            OvrRating = 92
                        },
                        new
                        {
                            Id = 111,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = true,
                            Name = "Casillas",
                            OvrRating = 90
                        },
                        new
                        {
                            Id = 112,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Lamine Yamal",
                            OvrRating = 89
                        },
                        new
                        {
                            Id = 113,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Pedri",
                            OvrRating = 88
                        },
                        new
                        {
                            Id = 114,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Dani Carvajal",
                            OvrRating = 83
                        },
                        new
                        {
                            Id = 115,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Iago Aspas",
                            OvrRating = 82
                        },
                        new
                        {
                            Id = 116,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Pedro Porro",
                            OvrRating = 81
                        },
                        new
                        {
                            Id = 117,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Dean Huijsen",
                            OvrRating = 79
                        },
                        new
                        {
                            Id = 118,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Eric Garcia",
                            OvrRating = 77
                        },
                        new
                        {
                            Id = 119,
                            CardImage = "tbd",
                            Country = "Spain",
                            IsIcon = false,
                            Name = "Pedro",
                            OvrRating = 74
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
